from enum import Enum

class GoalType(str, Enum):
    maintain = "maintain"
    cut = "cut"
    bulk = "bulk"

class MealType(str, Enum):
    breakfast = "breakfast"
    lunch = "lunch"
    dinner = "dinner"
    snack = "snack"

class ActivityType(str, Enum):
    running = "running"
    jogging = "jogging"
    walking = "walking"
    hiking = "hiking"
    cycling = "cycling"
    swimming = "swimming"
    rowing = "rowing"
    elliptical = "elliptical"
    weightlifting = "weightlifting"
    crossfit = "crossfit"
    hiit = "hiit"
    yoga = "yoga"
    pilates = "pilates"
    boxing = "boxing"
    basketball = "basketball"
    soccer = "soccer"
    tennis = "tennis"
    volleyball = "volleyball"
    golf = "golf"
    dance = "dance"
    martial_arts = "martial arts"
    stretching = "stretching"
    rock_climbing = "rock climbing"
    jump_rope = "jump rope"
    stair_climbing = "stair climbing"
    bodyweight = "bodyweight"    
    pickleball = "pickleball"